import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// CONFIGURATION: Deployment Path
// Sim, é uma prática muito comum e correta ("Hot Reload").
// Aponta diretamente para a pasta do plugin no seu vault de estudo.
const VAULT_PLUGIN_DIR = "C:\\Obsidian Vault\\Estudo\\.obsidian\\plugins\\pomodoro-task";

const copyFilesPlugin = {
    name: 'copy-to-vault',
    setup(build) {
        build.onEnd(async () => {
            try {
                if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
                    fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
                }
                
                fs.copyFileSync("main.js", path.join(VAULT_PLUGIN_DIR, "main.js"));
                fs.copyFileSync("manifest.json", path.join(VAULT_PLUGIN_DIR, "manifest.json"));
                if (fs.existsSync("styles.css")) {
                    fs.copyFileSync("styles.css", path.join(VAULT_PLUGIN_DIR, "styles.css"));
                }
                console.log(`[DEPLOY] Files copied to: ${VAULT_PLUGIN_DIR}`);
            } catch (e) {
                console.error("[DEPLOY ERROR] Failed to copy files:", e);
            }
        });
    },
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
    plugins: [copyFilesPlugin], // Register the copy plugin
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
